services:
  laravel-app:
    build:
      context: .
      dockerfile: ./configuration/app_conf/Dockerfile
    container_name: laravel-app
    working_dir: /var/www/html
    restart: unless-stopped
    tty: true
    environment:
      - DB_CONNECTION=${POSTGRES_DB_CONNECTION}
      - DB_HOST=${POSTGRES_DB_HOST}
      - DB_PORT=${POSTGRES_DB_PORT}
      - DB_DATABASE=${POSTGRES_DB_DATABASE}
      - DB_USERNAME=${POSTGRES_DB_USERNAME}
      - DB_PASSWORD=${POSTGRES_DB_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    volumes:
      -  type: bind
         source: ./laravel
         target: /var/www/html
    networks:
      - test-mini-network
    depends_on:
      postgres-18-alpine:
        condition: service_healthy
      redis-alpine:
        condition: service_healthy
        
  postgres-18-alpine:
    image: postgres:18.1-alpine3.23
    container_name: postgres-18-alpine
    restart: always
    tty: true
    environment:
      - POSTGRES_DB=${POSTGRES_DB_DATABASE}
      - POSTGRES_USER=${POSTGRES_DB_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_DB_PASSWORD}
      #- POSTGRES_SCHEMA=${POSTGRES_SCHEMA}
    ports:
      - "${POSTGRES_DB_HOST_PORT}:${POSTGRES_DB_PORT}"
    volumes:
      - ./configuration/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - type: volume
        source: postgres-18-data
        target: /var/lib/postgresql/data
    networks:
      - test-mini-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_DB_USERNAME} -d ${POSTGRES_DB_DATABASE}"]
      interval: 5s
      timeout: 5s
      retries: 5
         
  redis-alpine:
    image: redis:alpine
    container_name: redis-alpine
    restart: always
    #environment:
      #- REDIS_PASSWORD=${REDIS_PASSWORD}
    command: redis-server 
    ports:
      - "${REDIS_HOST_PORT}:${REDIS_PORT}"
    volumes:
      - redis-data:/data
    networks:
      - test-mini-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  nginx:
    image: nginx:1.27-alpine
    container_name: nginx-1-27-alpine
    restart: unless-stopped
    ports:
      - "${HTTP_HOST_PORT}:${HTTP_PORT}"
    volumes:
      - ./configuration/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./laravel:/var/www/html
    depends_on:
      - laravel-app
    networks:
      - test-mini-network

volumes:
  test-mini-app-data:
    name: test-mini-app-data-logs
  postgres-18-data:
    name: postgres-18-alpine-logs
  redis-data:
    name: redis-alpine-logs

  nginx-conf:
  nginx-host:
  nginx-html:
  nginx-certs:
  acme:
  
networks:
  test-mini-network:
    driver: bridge
    #in case network existing already and dont have to create it automatically
    #external: true
